// Generated by CoffeeScript 1.7.1
(function() {
  var config;
  config = {
    host: '{TYPE_URL_HERE}',
    defaultPort: 3000,
    debugMode:true, //creates snapshot of each url visited by bots
    snapshotPath:'{PATH_TO_SAVE_SNAPSHOTS}',
    memcached: {
      enabled: true,
      defaultHost: 'localhost',
      defaultPort: 11211,
      maxValue: 2097152,
      connectRetries: 5,
      key: '{KEY}'
    },
    logentries: {
      enabled: false,
      token: '{TOKEN}'
    },
    //THIS WHITELIST HAS BEEN DISABLED FOR A WHILE
    getParamWhitelist: ['page','st','srt','srb','p','lng','lat','at','in','svt','vt','fb','sst','rt','rrt','date','time','day','q','dt','ovt']
  };
  module.exports = config;
}).call(this);
